# Generated by Django 4.2.23 on 2025-07-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupé', 'Occupé')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.contrat')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_signalement', models.DateField()),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('résolu', 'Résolu')], max_length=50)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.maison')),
            ],
        ),
        migrations.AddField(
            model_name='contrat',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.locataire'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.maison'),
        ),
    ]
